# Предобработка данных датасета о продажах игр

### Цели и задачи проекта
В этой тетрадке используем датасет `new_games.csv`, который содержит информацию о продажах игр разных жанров и платформ, а также пользовательские и экспертные оценки игр. На примере датасета познакомимся с основными данными, проверим их на корректность и проведем предобработку, проведя необходимый срез данных.

### Описание данных
В проекте будут использованы данные датасета `new_games.csv` с таким описанием:
- `Name` — название игры.
- `Platform` — название платформы.
- `Year of Release` — год выпуска игры.
- `Genre` — жанр игры.
- `NA sales` — продажи в Северной Америке (в миллионах проданных копий).
- `EU sales` — продажи в Европе (в миллионах проданных копий).
- `JP sales` — продажи в Японии (в миллионах проданных копий).
- `Other sales` — продажи в других странах (в миллионах проданных копий).
- `Critic Score` — оценка критиков (от 0 до 100).
- `User Score` — оценка пользователей (от 0 до 10).
- `Rating` — рейтинг организации ESRB (англ. Entertainment Software Rating Board). Эта ассоциация определяет рейтинг компьютерных игр и присваивает им подходящую возрастную категорию.

### Содержимое проекта
1. Загрузка и знакомство с данными
2. Проверка ошибок в данных и их предобработка\
   2.1 Названия столбцов датафрейма\
   2.2 Типы данных\
       2.2.1 Корректировка типов данных\
   2.3 Наличие пропусков в данных\
   2.4 Явные и неявные дубликаты в данных
3. Фильтрация данных
4. Категоризация данных
5. Итоговый вывод

## 1. Загрузка и знакомство с данными

Загрузим необходимые библиотеки для анализа данных и данные из датасета `new_games.csv`. Затем выведем основную информацию о данных с помощью метода `info()` и первые строки датафрейма.

In [1]:
# Импортируем библиотеку pandas
import pandas as pd

In [2]:
# Выгружаем данные из датасета hotel_dataset.csv в датафрейм hotels
games = pd.read_csv('https://code.s3.yandex.net/datasets/new_games.csv')

## 2.Проверка ошибок в данных и их предобработка
### 2.1 Названия столбцов датафрейма

In [3]:
# Выводим первые строки датафрейма на экран
games.head()

,Name,Platform,Year of Release,Genre,NA sales,EU sales,JP sales,Other sales,Critic Score,User Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN

Необходимо привести все названия столбцов к единому стилю snake case

In [4]:
# Корректируем названия столбцов в соответствии со стилем snake case
games = games.rename(columns = lambda col: (col.strip().lower().replace(' ', '_')))
games.head()

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN

### 2.2 Типы данных

In [5]:
# Выводим информацию о датафрейме
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16954 non-null  object
 1   platform         16956 non-null  object
 2   year_of_release  16681 non-null  float64
 3   genre            16954 non-null  object
 4   na_sales         16956 non-null  float64
 5   eu_sales         16956 non-null  object
 6   jp_sales         16956 non-null  object
 7   other_sales      16956 non-null  float64
 8   critic_score     8242 non-null   float64
 9   user_score       10152 non-null  object
 10  rating           10085 non-null  object
dtypes: float64(4), object(7)
memory usage: 1.4+ MB

In [6]:
# Сохраняем количество строк в датасете до того, как начнем предобработку
count_rows_before = games.shape[0]
print(f'Изначальное количество строк в датасете: {count_rows_before}')

Изначальное количество строк в датасете: 16956

Датасет `new_games.csv` содержит 11 столбцов и 16956 строк, в которых представлена информация о продажах игр разных жанров и платформ.

Названия столбцов датасета были переименованы в соответствии со стилем snake case: `name`, `platform`, `year_of_release`, `genre`, `na_sales`, `eu_sales`, `jp_sales`, `other_sales`, `critic_score`, `user_score`, `rating`. Такой формат необходим для удобства чтения и поддержки чистоты кода

Изучим типы данных и их корректность:

- **Числовые значения с плавающей запятой (float64).** Четыре столбца имеют тип данных float64:
    - `year_of_release`- содержит год выпуска игры. Тип `float` может автоматически устанавливаться на столбцах с датой, где есть пропуски значений. Для анализа, возможно, нам не понадобится `datetime`, поэтому достаточно будет преобразовать в `int16` для "правильного" отображения в выводе, без плаващей точки.
    - `na_sales` - содержит продажи в Северной Америке, тип данных выбран корректно.
    - `other_sales` - содержит продажи в других странах, тип данных выбран корректно.
    - `critic_score` - содержит оценку критиков (от 0 до 100) в виде только целочисленных значений. Следовательно, оптимальным будет использовать тип даннх `int16`.
- **Строковые данные (object).** Семь столбцов имеют тип данных `object`:
    - `name`, `platform`, `genre` - содержат сроковую информацию (название игры, название платформы и жанр игры), что логично для текстовых данных. Здесь тип данных `object` подходит.
    - `rating` - также хранит текстовые данные. Но их можно рассматривать как категориальные признаки.
    - `eu_sales`, `jp_sales` содержат данные о продажах в формате вещественных чисел, поэтому тип данных неободимо заменить на float64.
    - `user_score` содержит оценки пользователей в формате вещественных чисел, поэтому тип данных неободимо заменить на float64.

После анализа типов данных видно, что некоторые столбцы представлены некорректно и необходимо преобразовать типы данных для оптимизации обработки. В числовых столбцах могут встретиться строковые значения, например `unknown` или другие, поэтому будем использовать команду `errors="coerce"` для замены строковых значений на пропуски.

Прежде чем изменить тип данных в столбце `user_score`, проверим какие значения там содержатся, потому что после перевода в `float64` мы потеряем эти данные.

In [7]:
games['user_score'].unique()

array(['8', nan, '8.3', '8.5', '6.6', '8.4', '8.6', '7.7', '6.3', '7.4',
       '8.2', '9', '7.9', '8.1', '8.7', '7.1', '3.4', '5.3', '4.8', '3.2',
       '8.9', '6.4', '7.8', '7.5', '2.6', '7.2', '9.2', '7', '7.3', '4.3',
       '7.6', '5.7', '5', '9.1', '6.5', 'tbd', '8.8', '6.9', '9.4', '6.8',
       '6.1', '6.7', '5.4', '4', '4.9', '4.5', '9.3', '6.2', '4.2', '6',
       '3.7', '4.1', '5.8', '5.6', '5.5', '4.4', '4.6', '5.9', '3.9',
       '3.1', '2.9', '5.2', '3.3', '4.7', '5.1', '3.5', '2.5', '1.9', '3',
       '2.7', '2.2', '2', '9.5', '2.1', '3.6', '2.8', '1.8', '3.8', '0',
       '1.6', '9.6', '2.4', '1.7', '1.1', '0.3', '1.5', '0.7', '1.2',
       '2.3', '0.5', '1.3', '0.2', '0.6', '1.4', '0.9', '1', '9.7'],
      dtype=object)

In [8]:
(games["user_score"] == "tbd").sum()

np.int64(2464)

Из последнего вычисления видим, что 2464 строки имеют значение 'tbd' в столбце `user_score`. Вполне вероятно, что TBD означает сокращение от английского выражения to be determined, которое переводится как «будет определено позже», «подлежит уточнению» или «будет решено позже». Доля таких значений велика, но мы не можем их вычислить арифметически. После перехода в тип `float64` эти данные превратятся в пропуски.

### 2.2.1 Корректировка типа данных

На стадии знакомства с данными было установлено, что для оптимизации возможно применение целочисленных типов с уменьшенной разрядностью (столбец `critic_score`), преобразование вещественных данных столбца `year_of_release` в целочисленный тип `int16`, преобразование строковых данных о продажах и оценках пользователей в `float64`.

In [9]:
# Преобразовываем столбец с годом выпуска игры в тип int16
games['year_of_release'] = games['year_of_release'].astype('Int16')

In [10]:
# Преобразовываем тип данных столбца critic_score из вещественного числа в целочисленный с пониженной разрядностью
games['critic_score'] = games['critic_score'].astype('Int16')

In [11]:
# Преобразовываем тип данных столбцов `eu_sales`, `jp_sales`, `user_score` в float64
for column in ['eu_sales', 'jp_sales', 'user_score']:
    games[column] = pd.to_numeric(games[column], errors="coerce")

In [12]:
# Проверяем результат преобразования
games[['year_of_release', 'critic_score', 'eu_sales', 'jp_sales', 'user_score']].dtypes

year_of_release      Int16
critic_score         Int16
eu_sales           float64
jp_sales           float64
user_score         float64
dtype: object

Для оптимизации работы с данными в датафрейме были сделаны такие изменения типов данных:
- `year_of_release`: тип данных изменён с `float64` на `int16`.
- `critic_score`: тип данных изменён с `float64` на `int16`.
- `eu_sales`, `jp_sales` и `user_score`: тип данных изменён с `object` на `float64`.

In [13]:
games.head()

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,Wii Sports,Wii,2006,Sports,41.36,28.96,3.77,8.45,76,8.0,E
1,Super Mario Bros.,NES,1985,Platform,29.08,3.58,6.81,0.77,<NA>,NaN,NaN
2,Mario Kart Wii,Wii,2008,Racing,15.68,12.76,3.79,3.29,82,8.3,E
3,Wii Sports Resort,Wii,2009,Sports,15.61,10.93,3.28,2.95,80,8.0,E
4,Pokemon Red/Pokemon Blue,GB,1996,Role-Playing,11.27,8.89,10.22,1.00,<NA>,NaN,NaN

### 2.3 Наличие пропусков в данных

В этом разделе посмотрим на количество пропущенных значений по столбцам датафрейма в асболютных и относительных значениях.

In [14]:
# Выводим количество пропущенных строк в датафрейме
#games.isna().sum()
pd.DataFrame(games.isna().sum()).style.background_gradient('coolwarm')

In [15]:
# Подсчитываем процент строк с пропусками
#games.isna().sum() / games.shape[0] * 100
pd.DataFrame(round(games.isna().mean()*100,2)).style.background_gradient('coolwarm')

В данных наблюдаются пропуски в следующих столбцах:
- `name`: в 2 строках (0.01% данных) отсутствует информация о названии игры. Это может затруднить идентификацию, если необходимо провести анализ по конкретным играм. Но доля пропусков не высокая и можно их не принимать во внимание.
- `year_of_release`: в 275 строках (1.62% данных) отсутствует информация о годе выпуска игры. Пропуски в этом столбце могут повлиять на анализ по временным признакам. Так как основная задача провести анализ среди игр, выпущенных за определенный временной период, а заменить эти пропуски статистическими данными мы не можем, и их доля не превышает 2%, то просто удалим эти строки из датасета.
- `genre` в 2 строках (0.01%) отсутствует информация о жанре игры. Возможно, это те же самые строки, где пропущены названия игр. Проверим это ниже в коде и удалим при необходимости.
- `eu_sales`: в 6 строках (0.035%) отсутствует информация о продажах, их можно заменить на среднее значение в зависимости от названия платформы и года выхода игры.
- `jp_sales`: в 4 строках (0.024%) отсутствует информация о продажах, их можно заменить на среднее значение в зависимости от названия платформы и года выхода игры.
- `critic_score`: в 8714 строках (51.39% данных) отсутствует информация об оценке критиков. Пропуски в этом столбце могут повлиять на фильтр по рейтингу игр. Автоматическая замена этих пропусков усредненными значениями может исказить выводы. Заменим пропуски метками "-1".
- `user_score`: в 9268 строках (54.66% данных) отсутствует информация об оценке пользователей. Автоматическая замена этих пропусков усредненными значениями может исказить выводы. Заменим пропуски метками "-1".
- `rating`: в 6871 строках (40.52% данных) отсутствует информация о рейтинге ESRB. Это ухудшает работу рекоммендательных систем. Заменим пропуски метками "-1".
- Проверим также "нулевые" продажи по всем трем регионам.

In [16]:
# Проверяем пропуски в строках `name` и `genre`
games[games['name'].isna()]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
661,NaN,GEN,1993,NaN,1.78,0.53,0.00,0.08,<NA>,NaN,NaN
14439,NaN,GEN,1993,NaN,0.00,0.00,0.03,0.00,<NA>,NaN,NaN

In [17]:
# Удаляем две строки по индексам:
games = games.drop(index=[661, 14439])

Напишем функцию для заполнения пропусков средним значением для группы `platform-year_of_release` и с помощью нее заполним пропуски в столбцах `eu_sales` и `jp_sales`

In [18]:
# Напишем функцию для заполнения пропусков средним значением
def fill_by_platform_year(df, column):
    group = df.groupby(['platform', 'year_of_release'])[column].transform('mean')
    df[column] = df[column].fillna(group)

# заполняем пропуски средними значениями в столбце 'eu_sales'
fill_by_platform_year(games, 'eu_sales')

# заполняем пропуски средними значениями в столбце 'jp_sales'
fill_by_platform_year(games, 'jp_sales')

In [19]:
# Проверяем наличие строк с пустыми продажами
games[
    (games["na_sales"] == 0)
    & (games["eu_sales"] == 0)
    & (games["jp_sales"] == 0)
    & (games["other_sales"] == 0)
]

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
16916,G1 Jockey 4 2008,PS3,2008,Sports,0.0,0.0,0.0,0.0,<NA>,NaN,NaN
16950,SCORE International Baja 1000: The Official Game,PS2,2008,Racing,0.0,0.0,0.0,0.0,<NA>,NaN,NaN

In [20]:
# Удаляем две строки без продаж
games = games.drop(index=[16916, 16950])

In [21]:
# Заменяем пропуски в оценках игры на метку "-1"
games[['critic_score', 'user_score', 'rating']] = (games[['critic_score', 'user_score', 'rating']].fillna(-1))

In [22]:
# Удаляем строки, где пропущен год выпуска игры
games = games.dropna(subset=["year_of_release"])

In [23]:
# Еще раз проверяем пропуски
pd.DataFrame(games.isna().sum()).style.background_gradient('coolwarm')

### 2.4 Явные и неявные дубликаты в данных
В этом разделе изучим уникальные значения в категориальных данных, например с названиями жанра игры, платформы, рейтинга и года выпуска. 
Проверим, встречаются ли среди данных неявные дубликаты, связанные с опечатками или разным способом написания.

Приведем к нижнему регистру значения в столбцах `name` и `genre`, чтобы найти возможные неявные дубликаты в разности написания.
Явные дубликаты будем искать по совпадению значений в столбцах `name` и `platform`.

In [24]:
# Приводим значения к нижнему регистру в столбце `name`
games['name'] = games['name'].str.lower()

In [25]:
# Приводим значения к нижнему регистру в столбце `genre`
games['genre'] = games['genre'].str.lower()

In [26]:
# Выводим уникальные значения столбца 'platform'
games['platform'].unique()

array(['Wii', 'NES', 'GB', 'DS', 'X360', 'PS3', 'PS2', 'SNES', 'GBA',
       'PS4', '3DS', 'N64', 'PS', 'XB', 'PC', '2600', 'PSP', 'XOne',
       'WiiU', 'GC', 'GEN', 'DC', 'PSV', 'SAT', 'SCD', 'WS', 'NG', 'TG16',
       '3DO', 'GG', 'PCFX'], dtype=object)

In [27]:
# Выводим уникальные значения столбца 'year_of_release'
games['year_of_release'].unique()

<IntegerArray>
[2006, 1985, 2008, 2009, 1996, 1989, 1984, 2005, 1999, 2007, 2010, 2013, 2004,
 1990, 1988, 2002, 2001, 2011, 1998, 2015, 2012, 2014, 1992, 1997, 1993, 1994,
 1982, 2016, 2003, 1986, 2000, 1995, 1991, 1981, 1987, 1980, 1983]
Length: 37, dtype: Int16

In [28]:
# Выводим уникальные значения столбца 'genre'
games['genre'].unique()

array(['sports', 'platform', 'racing', 'role-playing', 'puzzle', 'misc',
       'shooter', 'simulation', 'action', 'fighting', 'adventure',
       'strategy'], dtype=object)

In [29]:
# Выводим уникальные значения столбца 'rating'
games['rating'].unique()

array(['E', -1, 'M', 'T', 'E10+', 'K-A', 'AO', 'EC', 'RP'], dtype=object)

In [30]:
# Выводим уникальные значения столбца 'user_score'
games['user_score'].unique()

array([ 8. , -1. ,  8.3,  8.5,  6.6,  8.4,  8.6,  7.7,  6.3,  7.4,  8.2,
        9. ,  7.9,  8.1,  8.7,  7.1,  3.4,  5.3,  4.8,  3.2,  8.9,  6.4,
        7.8,  7.5,  2.6,  7.2,  9.2,  7. ,  7.3,  4.3,  7.6,  5.7,  5. ,
        9.1,  6.5,  8.8,  6.9,  9.4,  6.8,  6.1,  6.7,  5.4,  4. ,  4.9,
        4.5,  9.3,  6.2,  4.2,  6. ,  3.7,  4.1,  5.8,  5.6,  5.5,  4.4,
        4.6,  5.9,  3.9,  3.1,  2.9,  5.2,  3.3,  4.7,  5.1,  3.5,  2.5,
        1.9,  3. ,  2.7,  2.2,  2. ,  9.5,  2.1,  3.6,  2.8,  1.8,  3.8,
        0. ,  1.6,  9.6,  2.4,  1.7,  1.1,  0.3,  1.5,  0.7,  1.2,  2.3,
        0.5,  1.3,  0.2,  0.6,  1.4,  0.9,  1. ,  9.7])

In [31]:
# Ищем дубликаты по двум столбцам 'name' и 'platform'
dubl=games[games.duplicated(subset=['name','platform'], keep=False)]
dubl

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
267,batman: arkham asylum,PS3,2009,action,2.24,1.31,0.07,0.61,91,8.9,T
268,batman: arkham asylum,PS3,2009,action,2.24,1.31,0.07,0.61,91,8.9,T
367,james bond 007: agent under fire,PS2,2001,shooter,1.90,1.13,0.10,0.41,72,7.9,T
368,james bond 007: agent under fire,PS2,2001,shooter,1.90,1.13,0.10,0.41,72,7.9,T
606,madden nfl 13,PS3,2012,sports,2.11,0.22,0.00,0.23,83,5.5,E
...,...,...,...,...,...,...,...,...,...,...,...
16799,transformers: prime,Wii,2012,action,0.00,0.01,0.00,0.00,-1,-1.0,-1
16911,metal gear solid v: the definitive experience,XOne,2016,action,0.01,0.00,0.00,0.00,-1,-1.0,M
16912,metal gear solid v: the definitive experience,XOne,2016,action,0.01,0.00,0.00,0.00,-1,-1.0,M
16939,the longest 5 minutes,PSV,2016,action,0.00,0.00,0.01,0.00,-1,-1.0,-1
16940,the longest 5 minutes,PSV,2016,action,0.00,0.00,0.01,0.00,-1,-1.0,-1

- Столбцы `name` и `genre` приведены к нижнему регистру для устранения возможных опечаток.
- В категориальных столбцах `platform`, `year_of_release`, `genre` дубликаты не обнаружены.
- В столбце `rating` не найдены дубликаты, но есть значение, которое не было указано в описании к задаче: `K-A`. Это обозначение использовалось раньше, но в современном классификаторе ESRB оно переименовано в `Е`. Нет смысла корректировать эти значения, потому что они верные в соотстветствии с годом выпуска игры, но нужно помнить про этот нюанс при анализе.
- Найдены 476 дублирующих строк по значению столбоц `name` и `platform`, для чистого датасета все дубли нужно удалить.

In [32]:
# Удаляем дубликаты по двум столбцам `name` и `platform`, оставляя только первый из повтора
games = games.drop_duplicates(subset=['name', 'platform'], keep="first")

Проверяем получившиеся уникальные значения в столбцах `genre` и `rating`:

In [51]:
games['genre'].unique()

array(['sports', 'platform', 'racing', 'role-playing', 'puzzle', 'misc',
       'shooter', 'simulation', 'action', 'fighting', 'adventure',
       'strategy'], dtype=object)

In [52]:
games['rating'].unique()

array(['E', -1, 'M', 'T', 'E10+', 'K-A', 'AO', 'EC', 'RP'], dtype=object)

In [34]:
# Количество удаленных строк
count_rows_after = games.shape[0]
print(f"Было строк: {count_rows_before}")
print(f"Стало строк: {count_rows_after}")
print(f"Удалено строк: {count_rows_before - count_rows_after}")

Было строк: 16956
Стало строк: 16439
Удалено строк: 517

## 3. Фильтрация данных
По заданию нас интересует период с 2000 по 2013 год включительно. Отберем данные по этому показателю. Сохраним новый срез данных в отдельном датафрейме `df_actual`.

In [35]:
# Фильтруем датасет по годам от 2000 до 2013 включительно
df_actual = games.loc[games["year_of_release"].between(2000, 2013)].copy()
df_actual.head()

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,wii sports,Wii,2006,sports,41.36,28.96,3.77,8.45,76,8.0,E
2,mario kart wii,Wii,2008,racing,15.68,12.76,3.79,3.29,82,8.3,E
3,wii sports resort,Wii,2009,sports,15.61,10.93,3.28,2.95,80,8.0,E
6,new super mario bros.,DS,2006,platform,11.28,9.14,6.50,2.88,89,8.5,E
7,wii play,Wii,2006,misc,13.96,9.18,2.93,2.84,58,6.6,E

In [36]:
df_actual.info()

<class 'pandas.core.frame.DataFrame'>
Index: 12776 entries, 0 to 16954
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             12776 non-null  object
 1   platform         12776 non-null  object
 2   year_of_release  12776 non-null  Int16
 3   genre            12776 non-null  object
 4   na_sales         12776 non-null  float64
 5   eu_sales         12776 non-null  float64
 6   jp_sales         12776 non-null  float64
 7   other_sales      12776 non-null  float64
 8   critic_score     12776 non-null  Int16
 9   user_score       12776 non-null  float64
 10  rating           12776 non-null  object
dtypes: Int16(2), float64(5), object(4)
memory usage: 1.0+ MB

Мы отфильтровали новый датасет df_actual, который содержит 12776 строк и 11 столбцов.

## 4. Категоризация данных
Разделим все игры по оценкам пользователей и выделим такие категории: 
- высокая оценка (от 8 до 10 включительно),
- средняя оценка (от 3 до 8, не включая правую границу интервала),
- низкая оценка (от 0 до 3, не включая правую границу интервала).

In [37]:
# Категоризируем все игры по оценкам пользователей:
#- высокая оценка (от 8 до 10 включительно)
#- средняя оценка (от 3 до 8, не включая правую границу интервала)
#- низкая оценка (от 0 до 3, не включая правую границу интервала)

df_actual['user_grades'] = pd.cut(df_actual['user_score'], bins=[-1, 0, 3, 8, 10.1],
                                  labels=['Нет оценки', 'Низкая оценка', 'Средняя оценка', 'Высокая оценка'], right=False)
df_actual.head()

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,user_grades
0,wii sports,Wii,2006,sports,41.36,28.96,3.77,8.45,76,8.0,E,Высокая оценка
2,mario kart wii,Wii,2008,racing,15.68,12.76,3.79,3.29,82,8.3,E,Высокая оценка
3,wii sports resort,Wii,2009,sports,15.61,10.93,3.28,2.95,80,8.0,E,Высокая оценка
6,new super mario bros.,DS,2006,platform,11.28,9.14,6.50,2.88,89,8.5,E,Высокая оценка
7,wii play,Wii,2006,misc,13.96,9.18,2.93,2.84,58,6.6,E,Средняя оценка

Выведем количество оценок **пользователей** по сегментам и посчитаем их процентное отношение к общему числу:

In [40]:
# Суммируем количества по категориям
us_grades = df_actual.groupby('user_grades', observed=False).agg(
    count=('name', 'count')
).sort_values(by='count',ascending=False)

# Добавим столбец с процентным отношением:
us_grades['share'] = round(us_grades['count']/us_grades['count'].sum()*100,2)

# Выведем результат
us_grades

                count  share
user_grades
Нет оценки       6296  49.28
Средняя оценка   4080  31.93
Высокая оценка   2284  17.88
Низкая оценка     116   0.91

In [41]:
# В качестве проверки сравниваем сумму категориальных данных и общее количество строк в df_actual
df_actual.groupby('user_grades', observed=False)['name'].count().sum() == df_actual.shape[0]

np.True_

In [42]:
# Категоризируем все игры по оценкам критиков:
#- высокая оценка (от 80 до 100 включительно)
#- средняя оценка (от 30 до 80, не включая правую границу интервала)
#- низкая оценка (от 0 до 30, не включая правую границу интервала)

df_actual['critic_grades'] = pd.cut(df_actual['critic_score'], bins=[-1, 0, 30, 80, 101],
                                  labels=['Нет оценки', 'Низкая оценка', 'Средняя оценка', 'Высокая оценка'], right=False)
df_actual.head()

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,user_grades,critic_grades
0,wii sports,Wii,2006,sports,41.36,28.96,3.77,8.45,76,8.0,E,Высокая оценка,Средняя оценка
2,mario kart wii,Wii,2008,racing,15.68,12.76,3.79,3.29,82,8.3,E,Высокая оценка,Высокая оценка
3,wii sports resort,Wii,2009,sports,15.61,10.93,3.28,2.95,80,8.0,E,Высокая оценка,Высокая оценка
6,new super mario bros.,DS,2006,platform,11.28,9.14,6.50,2.88,89,8.5,E,Высокая оценка,Высокая оценка
7,wii play,Wii,2006,misc,13.96,9.18,2.93,2.84,58,6.6,E,Средняя оценка,Средняя оценка

Выведем количество оценок **критиков** по сегментам и посчитаем их процентное отношение к общему числу:

In [43]:
# Группируем количество оценок по сегментам:
crit_grades=df_actual.groupby('critic_grades', observed=False).agg(
    count=('name','count')
    ).sort_values(by='count',ascending=False)

# Добавим столбец с процентным отношением:
crit_grades['share'] = round(crit_grades['count']/crit_grades['count'].sum()*100,2)

# Выведем результат
crit_grades

                count  share
critic_grades
Нет оценки       5610  43.91
Средняя оценка   5422  42.44
Высокая оценка   1689  13.22
Низкая оценка      55   0.43

In [44]:
# В качестве проверки сравниваем сумму категориальных данных и общее количество строк в df_actual
df_actual.groupby('user_grades', observed=False)['name'].count().sum() == df_actual.shape[0]

np.True_

In [45]:
# Выведем Топ-7 платформ по количеству игр, выпущенных за весь актуальный период
df_actual["platform"].value_counts().head(7)

platform
PS2     2126
DS      2120
Wii     1275
PSP     1180
X360    1120
PS3     1085
GBA      811
Name: count, dtype: int64

## 5. Итоговый вывод

Были загружены данные `new_games.csv`. Они содержат 11 столбцов и 16956 строк, в которых представлена информация о продажах игр разных жанров и платформ.
При первичном знакомстве с данными и их предобработке получили такие результаты:
Названия столбцов были скорректированы под стандарт стиля snake case. У пяти столбцов данных были изменены типы данных:
- `year_of_release`: тип данных изменён с `float64` на `int16`.
- `critic_score`: тип данных изменён с `float64` на `int16`.
- `eu_sales`, `jp_sales` и `user_score`: тип данных изменён с `object` на `float64`
Отображение года реализации игры скорректировано после изменения типа данных.
Больше всего пропусков данных было найдено в трех столбцах:
`user_score` - 54%
` critic_score` - 51%
` rating` - 40%
Пропуски заполнили метками.
Найдено и устранено 476 строк дубликатов названий игр.
Всего очищено и удалено 517 строк.

Для детального анализа по заданным требованиям с фильтром по годам с 2000 по 2013 год был создан новый датафрейм `df_actual` на 12776 строк.

Проведены две категоризации данных по оценкам пользователей и оценкам критиков. Для этого в датасет добавлены два новых столбца `user_grades` и `critic_grades`. 
По итогам анализа сделаны следующие выводы:

32% пользователей поставили среднюю оценку играм, вышедшим за заданный период времени.\
18% пользователей поставили высокую оценку играм, вышедшим за заданный период времени.\
При этом 49% игр остались без оценок пользователей.

42% критиков поставили среднюю оценку играм, вышедшим за заданный период времени.\
13% критиков поставили высокую оценку играм, вышедшим за заданный период времени.\
При этом 44% игр остались без оценок критиков.

Платформа, на которой вышло больше всего игр за заданный период - PS2 (2126), почти столько же на платформе DS (2120)